DROP INDEX IDX_PLANNER_EMPLOYEE_UNIQ_PERSONAL_NUMBER;
UPDATE PLANNER_EMPLOYEE SET PERSONAL_NUMBER = '000000' WHERE PERSONAL_NUMBER IS NULL;
alter table PLANNER_EMPLOYEE alter column PERSONAL_NUMBER set not null ;
