-- begin PLANNER_VACATION
alter table PLANNER_VACATION add constraint FK_PLANNER_VACATION_ON_EMPLOYEE foreign key (EMPLOYEE) references PLANNER_EMPLOYEE(ID)^
create index IDX_PLANNER_VACATION_ON_EMPLOYEE on PLANNER_VACATION (EMPLOYEE)^
-- end PLANNER_VACATION
-- begin PLANNER_EMPLOYEE
create unique index IDX_PLANNER_EMPLOYEE_UNIQ_PERSONAL_NUMBER on PLANNER_EMPLOYEE (PERSONAL_NUMBER)^
-- end PLANNER_EMPLOYEE
